app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/fe', function () {
//     return view('/index');
// });


//Frontend Routes


Route::resource('ItemCRUD','ItemCRUDController');

Route::resource('/','fe\HomeController');
Route::resource('/howitworks', 'fe\HowitworksController');
Route::resource('/contactus', 'fe\ContactusController');
// 
// Route::get('/', 'fe\HomeController@show');
// Route::get('/howitworks', 'fe\HowitworksController@show');
// Route::get('/contactus', 'fe\ContactusController@show');
Route::get('/aboutus', 'fe\AboutusController@show');
Route::get('/ourservice', 'fe\OurserviceController@show');
Route::get('/blog', 'fe\BlogController@show');
Route::get('/recent', 'fe\RecentController@show');


//Backend Routes
Route::get('/pittsburghadmin', 'be\AdminController@show');
Route::post('/pittsburghadmin', 'be\AdminController@doLogin');
Route::get('/admindashboard', 'be\DashboardController@show');
// Route::get('/bannersmain', 'be\BannersControllerer@show');
// Route::get('/upload', 'be\BannersControllerer@upload');

Route::resource('/blogsmain', 'be\BlogsController');
Route::resource('/testimonialsmain', 'be\TestimonialsController');
Route::resource('/accountsmain', 'be\AccountsController');
Route::resource('/pagescontentmain', 'be\PagescontentController');
Route::resource('/homecontentmain', 'be\HomecontentController');
Route::resource('/bannersmain', 'be\BannersControllerer');
Route::resource('/areassmain', 'be\AreasController');

// Route::post('/testimonialsimg/store', 'be\TestimonialsController@imgstore');

Route::any( '/testimonialsimg', array(
            'as' => 'testimonials-img',
            'uses' => 'be\TestimonialsController@imgstore'
        ));

Route::any( '/testimonialsvid', array(
            'as' => 'testimonials-vidmain',
            'uses' => 'be\TestimonialsController@videomain'
        ));
Route::any( '/testimonialsvidcreate', array(
            'as' => 'testimonials-vidcreate',
            'uses' => 'be\TestimonialsController@videocreate'
        ));

Route::any( '/testimonialsvidstore', array(
            'as' => 'testimonials-vidstore',
            'uses' => 'be\TestimonialsController@videostore'
        ));

//listing
Route::get('/cashofferlist', 'fe\HomeController@belist');
Route::get('/questionlist', 'fe\HowitworksController@belist');
Route::get('/contactuslist', 'fe\ContactusController@belist');
Route::get('Areas/{id}', 'fe\HomeController@searvearea');
Route::get('{blogid}', 'fe\BlogController@blogview');

app/Http/Controllers/be/AccountsController.php
<?php

namespace App\Http\Controllers\be;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Accountes;

class AccountsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // return view('be.accounts_main');
        $id = '1';
        $item = Accountes::find($id);
        return view('be.accounts_main',compact('item'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
         $item = Accountes::find(1);
        return view('be.accounts_main',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       // $this->validate($request, [
       //      'title' => 'required',
       //      'content' => 'required',
       //      'page' => 'required',
       //      'autor' => 'required',
       //  ]);


        Accountes::find($id)->update($request->all());
        return redirect()->route('accountsmain.index')
                        ->with('success','Accounts has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/be/AdminController.php
<?php

namespace App\Http\Controllers\be;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
      return view('be.index');
    }

    public function doLogin()
    {
    // process the form
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/be/AreasController.php
<?php

namespace App\Http\Controllers\be;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Areas;

class AreasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       $items = Areas::orderBy('id','ASC')->paginate(5);
        return view('be.areas_main',compact('items'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $item = Areas::find($id);
        return view('be.areas_edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, [
        //     'title' => 'required',
        //     'content' => 'required',
        //     'page' => 'required',
        //     'autor' => 'required',
        // ]);


        Areas::find($id)->update($request->all());
        return redirect()->route('areassmain.index')
                        ->with('success','Area has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/be/BannersControllerer.php
<?php

namespace App\Http\Controllers\be;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use \Input as Input;
use App\Banners;


class BannersControllerer extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        //  $items = Banners::orderBy('id','DESC');
        // return view('be.banners',compact('items'));

        $items = Banners::orderBy('id','ASC')->paginate(15);
        return view('be.banners',compact('items'));
            
         // return view('be.banners');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            
                 $this->validate($request, [
                'path' => 'required',
                'page' => 'required',
                 ]); 

                 $file = Input::file('path');

                 $file->move('img', $file->getClientOriginalName());

                  $img_data = [
                    "path" => $file->getClientOriginalName(),
                    "page" => $request->page,
                ];

                 if ($request->page == 'home') {
                    $id = '1';
                    Banners::find($id)->update($img_data);
                    return redirect()->route('bannersmain.index')
                          ->with('success','Banners has been updated successfully');

                 }elseif ($request->page == 'about') {
                    $id = '2';
                    Banners::find($id)->update($img_data);
                    return redirect()->route('bannersmain.index')
                          ->with('success','Banners has been updated successfully');

                 }elseif ($request->page == 'service') {
                    $id = '3';
                    Banners::find($id)->update($img_data);
                    return redirect()->route('bannersmain.index')
                          ->with('success','Banners has been updated successfully');

                 }else {
                   $id = '4';
                    Banners::find($id)->update($img_data);
                    return redirect()->route('bannersmain.index')
                          ->with('success','Banners has been updated successfully');

                 }

                 // $getimageName = $request->path->getClientOriginalExtension();
                 // $request->path->move(public_path('img'), $getimageName);


               // Banners::create($img_data);   
               
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
      return view('be.banners');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('be.banners_update');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function upload(){
    if(Input::hasFile('file')){

            $file = Input::file('file');
            $file->move('img', $file->getClientOriginalName());

            if ($file) {
                
                echo "Mabuhay.. nagupload at nagsave na ang image";
                die();
            }
        }

    }

}

app/Http/Controllers/be/BlogsController.php
<?php

namespace App\Http\Controllers\be;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Blogs;
use \Input as Input;

class BlogsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $items = Blogs::orderBy('id','ASC')->paginate(5);
        return view('be.blog_main',compact('items'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
       // return view('be.blog_main');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('be.blog_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
            'slugs' => 'required',
            'author' => 'required',
            'thumbnail' => 'required',
        ]);
       // if(Input::hasFile('thumbnail')){

       $file = Input::file('thumbnail');
       $file->move('img', $file->getClientOriginalName());


                  $blog_data = [
                    "title" => $request->title,
                    "author" => $request->author,
                    "content" => $request->content,
                    "thumbnail" => $file->getClientOriginalName(),
                    "slugs" => str_replace(' ', '-', strtolower($request->slugs)),
                ];
      
        Blogs::create($blog_data);   
        return redirect()->route('blogsmain.index')
                        ->with('success','Blog created successfully');
         // }else{
         //     return redirect()->route('blogsmain.index')
         //                ->with('warning','Error in saving. try again later.');
         // }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
       return view('be.blog_main');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Blogs::find($id);
        return view('be.blog_edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
            'slugs' => 'required',
            'author' => 'required',
            'thumbnail' => 'required',
        ]);

        $file = Input::file('thumbnail');
       $file->move('img', $file->getClientOriginalName());


                  $blog_data = [
                    "title" => $request->title,
                    "author" => $request->author,
                    "content" => $request->content,
                    "thumbnail" => $file->getClientOriginalName(),
                    "slugs" => str_replace(' ', '-', strtolower($request->slugs)),
                ];

        Blogs::find($id)->update($blog_data);
        return redirect()->route('blogsmain.index')
                        ->with('success','Blog has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Blogs::find($id)->delete();
        return redirect()->route('blogsmain.index')
                        ->with('success','Blog has been deleted successfully');
    }
}

resources/views/be/areas_main.blade.php
<style type="text/css">
    
    .ellipsis {
    max-width: 80px;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}
</style>


<!-- head -->
  @include('includes.admin-head') 
    <div id="wrapper">
<!-- nav -->
      @include('includes.admin-nav') 
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">

<div align="right">
<!-- <button type="button" class="btn btn-primary">Add Testimonials</button> -->
 <!-- <a class="btn btn-primary" href="{{ route('testimonialsmain.create') }}"> Create New Item</a> -->
</div><br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
<!-- body here -->
<div class="panel panel-default">
                        <div class="panel-heading">
                            Areas We Serve
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                            
                                        <tr>
                                            <!-- <th>ID Number</th> -->
                                            <th>Title</th>
                                            <th max-width="120">Content</th>
                                            <th>Autor</th>
                                            <th>Action</th>
                                        </tr>
                                        @foreach ($items as $key => $item)
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <!-- <td>{{ $item->id }}</td> -->
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->slugs }}</td>
                                            <td class="ellipsis">{{ strip_tags($item->contentmain) }}</td>
                                            <td>
                                            <a class="btn btn-primary" href="{{ route('areassmain.edit',$item->id) }}">Update</a>
                                           <!--  {!! Form::open(['method' => 'DELETE','route' => ['testimonialsmain.destroy', $item->id],'style'=>'display:inline']) !!} -->
                                           <!--  {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!} -->
                                            {!! Form::close() !!}
                                            </td>
                                        </tr>
                                @endforeach
                                    </tbody>
                                </table>
                         {!! $items->render() !!}
                            </div>
                        </div>
                    </div>






<!-- end of body -->
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

<!-- footer -->
 @include('includes.admin-foot') 

resources/views/be/blog_create.blade.php
<!-- head -->
  @include('includes.admin-head') 
    <div id="wrapper">
<!-- nav -->
      @include('includes.admin-nav') 
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">

<div align="right">
<!-- <button type="button" class="btn btn-primary">Add Testimonials</button> -->
 <!-- <a class="btn btn-primary" href="{{ route('testimonialsmain.create') }}"> Create New Item</a> -->
</div><br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

<!-- body here -->
<div class="panel panel-default">
                        <div class="panel-heading">
                            Create Blogs
                        </div>
                        <div class="panel-body">

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
            {!! Form::open(array('route' => 'blogsmain.store','method'=>'POST','enctype'=>'multipart/form-data')) !!}
                    <div class="row">


                         <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Upload Tumbnail:</strong>
                                <label>Select image to upload:</label>
                                <input type="file" name="thumbnail" id="thumbnail">
                                <input type="hidden" value="{{ csrf_token() }}" name="_token">
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Title:</strong>
                                <!-- {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control')) !!} -->
                                <input type="text" id="title" placeholder="Title" class="form-control" name="title" onkeyup="populateSecondTextBox();">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Slugs:</strong>
                                <!-- {!! Form::text('title', null, array('placeholder' => 'slugs','class' => 'form-control')) !!} -->
                                <input type="text" id="slugs" placeholder="Title" class="form-control" name="slugs">
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Author:</strong>
                                {!! Form::text('author', null, array('placeholder' => 'Author Name','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Content:</strong>
                                <textarea class="form-control" id="summary-ckeditor" name="content"></textarea>

                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                        </div>


                    </div>
        {!! Form::close() !!}
                    </div>






<!-- end of body -->
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
<script type="text/javascript" src="{!! asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') !!}"></script>
<!-- <script src="{{ asset('') }}"></script> -->
<script>
    CKEDITOR.replace( 'summary-ckeditor' );
</script>

<script type="text/javascript">
function populateSecondTextBox() {
    document.getElementById('slugs').value = document.getElementById('title').value;
}
</script>
<!-- footer -->
 @include('includes.admin-foot') 

resources/views/be/contactus_main.blade.php
<style type="text/css">
    
    .ellipsis {
    max-width: 80px;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}
</style>


<!-- head -->
  @include('includes.admin-head') 
    <div id="wrapper">
<!-- nav -->
      @include('includes.admin-nav') 
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">

<div align="right">
<!-- <button type="button" class="btn btn-primary">Add Testimonials</button> -->
 <!-- <a class="btn btn-primary" href="{{ route('testimonialsmain.create') }}"> Create New Item</a> -->
</div><br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
<!-- body here -->
<div class="panel panel-default">
                        <div class="panel-heading">
                            Contact us Datalist
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                            
                                        <tr>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Email</th>
                                            <th>Subject</th>
                                            <th>Message</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                        @foreach ($items as $key => $item)
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->phone }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->subject }}</td>
                                            <td class="ellipsis">{{ $item->message }}</td>
                                            <td class="ellipsis">{{ $item->created_at }}</td>
                                            <td>
                                            <!-- <a class="btn btn-info" href="{{ route('ItemCRUD.show',$item->id) }}">Show</a> -->
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#showmodal{{ $item->name }}">
                                              Show
                                            </button>

                                            </td>
                                            
                                        </tr>



                                    <div class="modal fade" id="showmodal{{ $item->name }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Contact us Details</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                            </button>
                                          </div>
                                          <div class="modal-body">
                                           <b>Name:</b> {{ $item->name }}<br>
                                           <b>Phone:</b> {{ $item->phone }}<br>
                                           <b>Email:</b> {{ $item->email }}<br>
                                           <b>Subject:</b> {{ $item->email }}<br>
                                           <b>Message:</b> {{ $item->message }}<br>

                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                          </div>
                                        </div>
                                      </div>
                                    </div>

























                                @endforeach
                                    </tbody>
                                </table>
                         {!! $items->render() !!}
                            </div>
                        </div>
                    </div>


<!-- end of body -->
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->


<!-- Modal -->







<!-- footer -->
 @include('includes.admin-foot') 